services:
  - type: web
    name: interpretable-ai-shap-framework
    env: python
    buildCommand: pip install -r requirements.txt && python generate_data.py
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
